apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.chain_namespace }}
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedNamespace
metadata:
  name: {{ .Values.chain_namespace }}
  namespace: {{ .Values.chain_namespace }}
spec:
  placement:
    clusters:
    - name: cita1
    - name: cita2
